"""
This is a setup.py script generated by py2applet

Usage:
		python setup.py py2app
"""

from setuptools import setup

APP = ['code/trivia.py']
DATA_FILES = ['data/Answers2.txt', 'data/Questions2.txt']
OPTIONS = {'argv_emulation': True,
			'iconfile': 'data/trivia_icon.png',
			'plist': {
				'PyRuntimeLocations': [
				'/Users/matt/opt/anaconda3/envs/trivia/lib/libpython3.7m.dylib']
					 }
		   }

setup(
		app=APP,
		data_files=DATA_FILES,
		options={'py2app': OPTIONS},
		setup_requires=['py2app'],
)
